[package]
name = "zeno-state"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
thiserror.workspace = true
zeno-codec = { path = "../zeno-codec" }
zeno-hash = { path = "../zeno-hash" }
zeno-storage = { path = "../zeno-storage" }
zeno-types = { path = "../zeno-types" }

[lints]
workspace = true
