[package]
name = "zeno-genesis"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
zeno-config = { path = "../zeno-config" }
zeno-crypto = { path = "../zeno-crypto" }
zeno-types = { path = "../zeno-types" }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
