[package]
name = "zeno-execution"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
zeno-crypto = { path = "../zeno-crypto" }
zeno-evm = { path = "../zeno-evm" }
zeno-hash = { path = "../zeno-hash" }
zeno-primitives = { path = "../zeno-primitives" }
zeno-state = { path = "../zeno-state" }
zeno-storage = { path = "../zeno-storage" }
zeno-types = { path = "../zeno-types" }

[lints]
workspace = true
